watch_stylesheet: true
watch_config: true

bars:
  yasb-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: false
      acrylic: false
      dark: false
    window_flags:
      always_on_top: true
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 35
    padding:
      top: 0
      left: 3
      bottom: 0
      right: 3
    widgets:
      left:   ["open_startmenu", "active_window"]
      center: []
      right:  ["disk", "separator", "cpu", "separator", "memory", "separator", "volume", "separator", "wifi", "separator", "battery", "separator", "clock"]

widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">{win[title]}</span>"
      label_alt: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]</span>"
      label_no_window: ""
      max_length: 48
      max_length_ellipsis: "..."
      monitor_exclusive: true

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">BAT <span style=\"color: #C5C8C6\">{percent}%</span></span>"
      time_remaining_natural: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
        label: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">{%H:%M}</span>"
        label_alt: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">{%a %d %b %Y %H:%M:%S}</span>"

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">CPU <span style=\"color: #C5C8C6\">{info[percent][total]:.0f}%</span></span>"
      label_alt: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">CPU: <span style=\"color: #C5C8C6\">{info[percent][total]}% | freq: {info[freq][current]:.2f} Mhz</span></span>"
      update_interval: 500

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
        label: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">RAM <span style=\"color: #C5C8C6\">{virtual_mem_free}</span></span>"
        label_alt: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">RAM <span style=\"color: #C5C8C6\">{virtual_mem_percent}%</span></span>"
        update_interval: 5000
        callbacks:
          on_right: "exec cmd /c Taskmgr"

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
        label: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">{iface_name}\t<span style=\"color: #C5C8C6\">{wifi_name}</span></span>"
        label_alt: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">{iface_name}\t<span style=\"color: #C5C8C6\">{iface_ip}</span></span>"
        update_interval: 5000
        wifi_icons:
          - "\udb82\udd2e"  # 0% strength (no wifi)
          - "\udb82\udd1f"  # 1-25% strength
          - "\udb82\udd22"  # 26-50% strength
          - "\udb82\udd25"  # 51-75% strength
          - "\udb82\udd28"  # 76-100% strength. Alternate theming: \uf1eb
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec cmd.exe /c start ms-settings:network"

  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">{volume_label} <span style=\"color: #C5C8C6\">{space[used][percent]:.1f}%</span></span>"
        label_alt: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">{volume_label} <span style=\"color: #C5C8C6\">{space[used][gb]:.1f}GB / {space[total][gb]:.1f}GB</span></span>"
        volume_label: "C:"
        update_interval: 60000
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec cmd.exe /c start ms-settings:network"

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
        label: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">VOL <span style=\"color: #C5C8C6\">{volume[percent]}</span></span>"
        label_alt: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">VOL <span style=\"color: #C5C8C6\">{volume[percent]}</span></span>"
        update_interval: 100
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec cmd.exe /c start ms-settings:network"

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
        label: "\ueb01 \ueab4 {download_speed} | \ueab7 {upload_speed}"
        label_alt: "\ueb01 \ueab4 {upload_speed} | \ueab7 {download_speed}"
        update_interval: 1000 # Update interval should be a multiple of 1000
        callbacks:
          on_right: "exec cmd /c Taskmgr"

  # Some custom widgets

  open_startmenu:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span style=\"font-family: 'Font Awesome 5 Free Solid'\">\uf0c9</span>"
      label_alt: "Start Menu"
      class_name: "start_widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: exec cscript /B C:\Users\Eirik\.yasb\scripts\open_startmenu.vbs

  explorer_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf07c"
      label_alt: "Explorer"
      class_name: "explorer-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec explorer.exe"
        on_right: "toggle_label"

  ip_info:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span style=\"color: #C5C8C6; font-family: 'Meslo LGLDZ Nerd Font Mono'\">{data[ip]}</span></span>"
      label_alt: "<span style=\"color: #C5C8C6; font-family: 'Meslo LGLDZ Nerd Font Mono'\">{data[city]}, {data[region]}, [{data[country]}]</span></span>"
      class_name: "ip-info-widget"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000                                        # every 5 minutes
        return_format: "json"
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl"                           # open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # open ipinfo in browser

  weather:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf0c2 {data[current_condition][0][temp_C]}\u00b0c"
      label_alt: "\uf0c2 {data[current_condition][0][weatherDesc][0][value]}"
      class_name: "weather-widget"
      exec_options:
        run_cmd: "curl.exe  wttr.in/Vancouver?format=j1"
        # run every hour
        run_interval: 3600000
        return_format: "json"

  separator:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">|</span>"
      label_alt: "<span style=\"font-family: 'Meslo LGLDZ Nerd Font Mono'\">|</span>"
      class_name: "separator-widget"
      exec_options:
        run_cmd: ""
        run_interval: 3600000
        return_format: "json"